### ISSUE TITLE
wttr.in script misses "-" if it's minus degrees

### ISSUE THREAD

**Issue by CorePoint** [dvogt23/dotfiles#1]
Hey,
very nice wttr.in script!
One thing though it misses the "-" between the icon and the first digit if it's minus degrees.

Thank you for making your dotfiles public, otherwise i would still be searching for such a good made script for my polybar. 

edit:

just made some tests again and it misses the "-" before the second digit too.

**Comment by CorePoint** [comment]
Fixed with https://github.com/dvogt23/dotfiles/pull/2. Thanks @alyptik

**Comment by dvogt23** [comment]
Thanks for the fix :+1:
